#text = "Lorem ipsum dolor sit amet"
text = """
package: name='com.miHoYo.GenshinImpact' versionCode='364' versionName='2.6.0_6179196_6305792' platformBuildVersionName='11' platformBuildVersionCode='30' compileSdkVersion='30' compileSdkVersionCodename='11'
install-location:'preferExternal'
minSdkVersion:'21'
targetSdkVersion:'30'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.FLASHLIGHT'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.CHANGE_NETWORK_STATE'
uses-permission: name='com.android.vending.BILLING'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
application-label:'Genshin Impact'
application-label-af:'Genshin Impact'
application-label-am:'Genshin Impact'
application-label-ar:'Genshin Impact'
application-label-as:'Genshin Impact'
application-label-az:'Genshin Impact'
application-label-be:'Genshin Impact'
application-label-bg:'Genshin Impact'
application-label-bn:'Genshin Impact'
application-label-bs:'Genshin Impact'
application-label-ca:'Genshin Impact'
application-label-cs:'Genshin Impact'
application-label-da:'Genshin Impact'
application-label-de:'Genshin Impact'
application-label-el:'Genshin Impact'
application-label-en:'Genshin Impact'
application-label-en-AU:'Genshin Impact'
application-label-en-CA:'Genshin Impact'
application-label-en-GB:'Genshin Impact'
application-label-en-IN:'Genshin Impact'
application-label-en-XC:'Genshin Impact'
application-label-es:'Genshin Impact'
application-label-es-ES:'Genshin Impact'
application-label-es-US:'Genshin Impact'
application-label-et:'Genshin Impact'
application-label-eu:'Genshin Impact'
application-label-fa:'Genshin Impact'
application-label-fi:'Genshin Impact'
application-label-fr:'Genshin Impact'
application-label-fr-CA:'Genshin Impact'
application-label-gl:'Genshin Impact'
application-label-gu:'Genshin Impact'
application-label-hi:'Genshin Impact'
application-label-hr:'Genshin Impact'
application-label-hu:'Genshin Impact'
application-label-hy:'Genshin Impact'
application-label-id:'Genshin Impact'
application-label-in:'Genshin Impact'
application-label-is:'Genshin Impact'
application-label-it:'Genshin Impact'
application-label-iw:'Genshin Impact'
application-label-ja:'原神'
application-label-ka:'Genshin Impact'
application-label-kk:'Genshin Impact'
application-label-km:'Genshin Impact'
application-label-kn:'Genshin Impact'
application-label-ko:'원신'
application-label-ky:'Genshin Impact'
application-label-lo:'Genshin Impact'
application-label-lt:'Genshin Impact'
application-label-lv:'Genshin Impact'
application-label-mk:'Genshin Impact'
application-label-ml:'Genshin Impact'
application-label-mn:'Genshin Impact'
application-label-mr:'Genshin Impact'
application-label-ms:'Genshin Impact'
application-label-my:'Genshin Impact'
application-label-nb:'Genshin Impact'
application-label-ne:'Genshin Impact'
application-label-nl:'Genshin Impact'
application-label-or:'Genshin Impact'
application-label-pa:'Genshin Impact'
application-label-pl:'Genshin Impact'
application-label-pt:'Genshin Impact'
application-label-pt-BR:'Genshin Impact'
application-label-pt-PT:'Genshin Impact'
application-label-ro:'Genshin Impact'
application-label-ru:'Genshin Impact'
application-label-si:'Genshin Impact'
application-label-sk:'Genshin Impact'
application-label-sl:'Genshin Impact'
application-label-sq:'Genshin Impact'
application-label-sr:'Genshin Impact'
application-label-sr-Latn:'Genshin Impact'
application-label-sv:'Genshin Impact'
application-label-sw:'Genshin Impact'
application-label-ta:'Genshin Impact'
application-label-te:'Genshin Impact'
application-label-th:'Genshin Impact'
application-label-tl:'Genshin Impact'
application-label-tr:'Genshin Impact'
application-label-uk:'Genshin Impact'
application-label-ur:'Genshin Impact'
application-label-uz:'Genshin Impact'
application-label-vi:'Genshin Impact'
application-label-zh:'原神'
application-label-zh-CN:'原神'
application-label-zh-HK:'原神'
application-label-zh-MO:'原神'
application-label-zh-TW:'原神'
application-label-zu:'Genshin Impact'
application-icon-160:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-240:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-320:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-480:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-640:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-65534:'res/mipmap-anydpi-v26/ic_launcher.xml'
application: label='Genshin Impact' icon='res/mipmap-anydpi-v26/ic_launcher.xml'
application-isGame
launchable-activity: name='com.miHoYo.GetMobileInfo.MainActivity'  label='Genshin Impact' icon=''
leanback-launchable-activity: name='com.miHoYo.GetMobileInfo.MainActivity'  label='Genshin Impact' icon='' banner=''
feature-group: label=''
  uses-gl-es: '0x30001'
  uses-feature-not-required: name='android.hardware.camera'
  uses-feature-not-required: name='android.hardware.camera.autofocus'
  uses-feature: name='android.hardware.opengles.aep'
  uses-feature-not-required: name='android.hardware.sensor.accelerometer'
  uses-feature-not-required: name='android.hardware.touchscreen'
  uses-feature-not-required: name='android.hardware.touchscreen.multitouch'
  uses-feature-not-required: name='android.hardware.touchscreen.multitouch.distinct'
  uses-feature-not-required: name='android.hardware.vulkan'
  uses-feature: name='android.hardware.screen.landscape'
  uses-implied-feature: name='android.hardware.screen.landscape' reason='one or more activities have specified a landscape orientation'
  uses-feature: name='android.hardware.wifi'
  uses-implied-feature: name='android.hardware.wifi' reason='requested android.permission.ACCESS_WIFI_STATE permission'
main
other-activities
other-receivers
other-services
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'af' 'am' 'ar' 'as' 'az' 'be' 'bg' 'bn' 'bs' 'ca' 'cs' 'da' 'de' 'el' 'en' 'en-AU' 'en-CA' 'en-GB' 'en-IN' 'en-XC' 'es' 'es-ES' 'es-US' 'et' 'eu' 'fa' 'fi' 'fr' 'fr-CA' 'gl' 'gu' 'hi' 'hr' 'hu' 'hy' 'id' 'in' 'is' 'it' 'iw' 'ja' 'ka' 'kk' 'km' 'kn' 'ko' 'ky' 'lo' 'lt' 'lv' 'mk' 'ml' 'mn' 'mr' 'ms' 'my' 'nb' 'ne' 'nl' 'or' 'pa' 'pl' 'pt' 'pt-BR' 'pt-PT' 'ro' 'ru' 'si' 'sk' 'sl' 'sq' 'sr' 'sr-Latn' 'sv' 'sw' 'ta' 'te' 'th' 'tl' 'tr' 'uk' 'ur' 'uz' 'vi' 'zh' 'zh-CN' 'zh-HK' 'zh-MO' 'zh-TW' 'zu'
densities: '160' '240' '320' '480' '640' '65534'
native-code: 'arm64-v8a'
"""

print(text)